name: Queen Erin's Site
markdown: redcarpet
pygments: true
baseurl: /qerin
authors:
erholmes:
  name: Erin Holmes
  prof: false
  gravatar:
  website: http://www.linkedin.com/in/holmeserin
  github: erholmes
  twitter: erinh24
  about: Erin is a second year MSIS student and is trying her best at life!
